// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/search-pokemon-cards.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function publicClient() {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_pokemon_cards_default = defineTool({
  name: "search_pokemon_cards",
  title: "Search Pok\xE9mon cards",
  description: "Search the CollectX Pok\xE9mon card catalog by name and/or set ID. Returns up to `limit` cards (default 20, max 50).",
  inputSchema: {
    name: z.string().trim().min(1).optional().describe("Card name (partial match)."),
    setId: z.string().trim().min(1).optional().describe("Set ID to filter by."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results, default 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ name, setId, limit }) => {
    const supabase = publicClient();
    let q = supabase.from("pokemon_cards").select("id, name, number, rarity, set_id, image_small").limit(limit ?? 20);
    if (name) q = q.ilike("name", `%${name}%`);
    if (setId) q = q.eq("set_id", setId);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { cards: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-collection.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function userClient(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_collection_default = defineTool2({
  name: "list_my_collection",
  title: "List my collection",
  description: "List the signed-in user's collected cards. Optionally filter by name or for_trade flag.",
  inputSchema: {
    name: z2.string().trim().min(1).optional().describe("Filter by card name (partial match)."),
    forTradeOnly: z2.boolean().optional().describe("If true, only return cards marked for trade."),
    limit: z2.number().int().min(1).max(100).optional().describe("Max results, default 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ name, forTradeOnly, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = userClient(ctx).from("user_cards").select(
      "id, card_id, card_name, card_number, condition, grading_company, grade_score, for_trade, for_sale, product_type, quantity, created_at"
    ).eq("user_id", ctx.getUserId()).limit(limit ?? 50);
    if (name) q = q.ilike("card_name", `%${name}%`);
    if (forTradeOnly) q = q.eq("for_trade", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { cards: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/list-my-trades.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function userClient2(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_trades_default = defineTool3({
  name: "list_my_trades",
  title: "List my trades",
  description: "List trades where the signed-in user is a participant (initiator or recipient). Optionally filter by status.",
  inputSchema: {
    status: z3.enum(["proposed", "accepted", "shipped", "completed", "disputed", "cancelled"]).optional().describe("Filter by trade status."),
    limit: z3.number().int().min(1).max(100).optional().describe("Max results, default 25.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const uid = ctx.getUserId();
    let q = userClient2(ctx).from("trades").select("id, status, initiator_user_id, recipient_user_id, created_at, updated_at").or(`initiator_user_id.eq.${uid},recipient_user_id.eq.${uid}`).order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { trades: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/list-marketplace-listings.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.103.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
function userClient3(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_marketplace_listings_default = defineTool4({
  name: "list_marketplace_listings",
  title: "List marketplace listings",
  description: "Browse active card-for-card marketplace listings. Optionally filter by card name.",
  inputSchema: {
    name: z4.string().trim().min(1).optional().describe("Filter by card name (partial match)."),
    limit: z4.number().int().min(1).max(50).optional().describe("Max results, default 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ name, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = userClient3(ctx).from("marketplace_listings").select("id, user_id, card_id, card_name, condition, quantity, status, created_at").eq("status", "active").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (name) q = q.ilike("card_name", `%${name}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { listings: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vnyhkqaxkhmbpzfhhztu";
var mcp_default = defineMcp({
  name: "collectx-mcp",
  title: "CollectX MCP",
  version: "0.1.0",
  instructions: "Tools for CollectX \u2014 the Pok\xE9mon card trading and collection platform. Search the card catalog, browse marketplace listings, and read the signed-in user's collection and trades.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_pokemon_cards_default, list_my_collection_default, list_my_trades_default, list_marketplace_listings_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
