// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqhakwqpetnatbyckhux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xaGFrd3FwZXRuYXRieWNraHV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NjIxNjMsImV4cCI6MjA1ODAzODE2M30.I1q9LtKKiuRYkXHM_igymQ919n_rnBKPlJccyBdRXfk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);