// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Lovable Cloud injects VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY.
// The hardcoded values are fallbacks for local dev without a .env file.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "https://kitejduabjzmhraiyzre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? import.meta.env.VITE_SUPABASE_ANON_KEY ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpdGVqZHVhYmp6bWhyYWl5enJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjczNjcsImV4cCI6MjA2OTU0MzM2N30.CYRsGXRWi3EKXaK8bG6WpeWKM8M8R__l0TcrrBwaCWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
